import pandas as pd
import csv
from sklearn.feature_extraction.text import TfidfVectorizer

# specify the file path correctly
file_path = '../data/abstracts_train.csv'

# load the data while handling quotes correctly and using tab as the delimiter
abstracts_train = pd.read_csv(file_path, quoting=csv.QUOTE_MINIMAL, delimiter='\t', on_bad_lines='skip')

# print the first few rows to check the data
print(abstracts_train.head())

# step 1: Preprocess the text (remove stopwords, tokenize, and lemmatize)
from nltk.tokenize import wordpunct_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk

# download necessary NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')

# initialize lemmatizer and stopwords
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # tokenize and clean the text
    tokens = wordpunct_tokenize(text.lower())  # Tokenize the text
    # lemmatize and remove stopwords
    return ' '.join([lemmatizer.lemmatize(word) for word in tokens if word.isalnum() and word not in stop_words])

# preprocess the abstracts in the dataframe
abstracts_train['processed_abstract'] = abstracts_train['abstract'].apply(preprocess_text)

# step 2: Apply the TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=6853)  # Adjust number of features if needed
X = vectorizer.fit_transform(abstracts_train['processed_abstract'])  # Transform the abstracts into feature vectors

# step 3: Save the vectorizer to use for future predictions
import joblib
joblib.dump(vectorizer, 'models/tfidf_vectorizer.pkl')

# print the shape of the resulting matrix
print(f'Feature matrix shape: {X.shape}')

# check the feature names generated by the vectorizer
print(f'Feature names: {vectorizer.get_feature_names_out()[:10]}')